services:

  db:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432




  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  adonis_app:
    container_name: 'planet-alert-backend'
    image: "sportek/planet-alert-backend:${IMAGE_TAG:-latest}"
    restart: 'unless-stopped'
    ports:

      - '3333:3333'
    env_file:
      - .env.production
    depends_on:
      - db
    command: >
      sh -c "node ace migration:run --force && node ace serve"
    logging:
      driver: "json-file"
      options:


        max-size: "10m"
        max-file: "3"

